name: CI/CD Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    name: Continuous Integration
    runs-on: windows-latest
    env:
      pathToSolution: ApiVersioning.sln
      testResultsFolderName: Test results
      publishOutputFolderName: Publish output
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)
